"use client";

import { motion } from "framer-motion";
import { FileText, Scale, AlertTriangle, CreditCard, XCircle, Gavel } from "lucide-react";

const sections = [
  {
    icon: FileText,
    title: "Acceptance of Terms",
    content: `By accessing or using Matt AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.

We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting. Your continued use of the Service constitutes acceptance of the updated terms.`
  },
  {
    icon: Scale,
    title: "Description of Service",
    content: `Matt AI provides an AI agent deployment platform that allows users to:

• Create custom AI-powered Telegram bots
• Configure agent capabilities and behaviors
• Deploy agents powered by Kimi K2.5 and Devin AI
• Manage agent subscriptions and billing

We do not guarantee specific outcomes or performance levels. AI responses are generated by third-party models and may vary in accuracy and appropriateness.`
  },
  {
    icon: CreditCard,
    title: "Payments & Refunds",
    content: `**Pricing**: All prices are displayed in USD and are subject to change with notice.

**Payment Terms**: 
• Setup fee: $150 one-time charge per agent
• Monthly subscription: $150/month
• Annual subscription: $1000/year (discounted)

**Refunds**:
• Setup fees are non-refundable once deployment begins
• Subscription refunds are handled on a case-by-case basis
• Contact support@meetmatt.xyz within 7 days for refund requests

**Cancellation**: You may cancel your subscription at any time. Access continues until the end of the billing period.`
  },
  {
    icon: AlertTriangle,
    title: "Prohibited Uses",
    content: `You agree not to use the Service to:

• Create agents for illegal activities or fraud
• Harass, abuse, or harm others
• Generate spam or unwanted communications
• Infringe on intellectual property rights
• Distribute malware or malicious content
• Circumvent security measures
• Violate Telegram&apos;s Terms of Service

Violation may result in immediate termination of your account without refund.`
  },
  {
    icon: XCircle,
    title: "Limitation of Liability",
    content: `**No Warranty**: The Service is provided &quot;as is&quot; without warranties of any kind, either express or implied.

**Limitation**: To the maximum extent permitted by law, Matt AI shall not be liable for:
• Indirect, incidental, or consequential damages
• Loss of profits, data, or business opportunities
• Service interruptions or data loss
• AI-generated content accuracy or appropriateness

**Maximum Liability**: Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.`
  },
  {
    icon: Gavel,
    title: "Governing Law & Disputes",
    content: `**Governing Law**: These terms are governed by the laws of [Jurisdiction], without regard to conflict of law principles.

**Dispute Resolution**: 
• We encourage informal resolution first — contact support@meetmatt.xyz
• Formal disputes shall be resolved through binding arbitration
• Class action waiver: Disputes must be brought individually

**Severability**: If any provision is found unenforceable, the remaining terms remain in effect.`
  }
];

export default function TermsPage() {
  return (
    <div className="pt-14 pb-12">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center py-12"
        >
          <div className="w-16 h-16 mx-auto mb-6 rounded-2xl bg-[var(--accent)]/10 flex items-center justify-center">
            <FileText className="w-8 h-8 text-[var(--accent)]" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="text-[var(--muted)] text-lg">Last updated: February 2025</p>
        </motion.div>

        {/* Intro */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6 mb-8"
        >
          <p className="text-[var(--muted)] leading-relaxed">
            Welcome to Matt AI. These Terms of Service govern your use of our AI agent deployment platform. Please read them carefully before using our services. By using Matt AI, you agree to comply with these terms.
          </p>
        </motion.div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.1 }}
              className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-[var(--accent)]/10 flex items-center justify-center flex-shrink-0">
                  <section.icon className="w-5 h-5 text-[var(--accent)]" />
                </div>
                <h2 className="text-xl font-semibold">{section.title}</h2>
              </div>
              <div className="text-[var(--muted)] leading-relaxed whitespace-pre-line text-sm">
                {section.content}
              </div>
            </motion.div>
          ))}
        </div>

        {/* Contact */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="mt-8 bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6"
        >
          <h2 className="text-lg font-semibold mb-2">Questions?</h2>
          <p className="text-sm text-[var(--muted)] mb-4">
            If you have any questions about these Terms of Service, please contact us:
          </p>
          <a 
            href="mailto:support@meetmatt.xyz" 
            className="text-[var(--accent)] hover:underline text-sm"
          >
            support@meetmatt.xyz
          </a>
        </motion.div>

        {/* Footer */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.9 }}
          className="mt-12 text-center text-sm text-[var(--muted)]"
        >
          <p>By using Matt AI, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.</p>
        </motion.div>
      </div>
    </div>
  );
}
