// Comprehensive Website Content for CMS
// This file contains all text content from the website that can be managed via the admin panel

export interface ContentItem {
  section: string;
  key: string;
  value: string;
  type: "text" | "markdown" | "html" | "json";
  description?: string;
}

// Website Content - organized by page/section
export const defaultWebsiteContent: ContentItem[] = [
  // ============ GLOBAL / NAVIGATION ============
  {
    section: "global",
    key: "site_title",
    value: "MeetMatt - AI Agents for Everyone",
    type: "text",
    description: "Website title shown in browser tab",
  },
  {
    section: "global",
    key: "site_description",
    value: "Deploy your own AI agent in minutes. Custom AI agents that work 24/7 for your business.",
    type: "text",
    description: "Meta description for SEO",
  },
  {
    section: "global",
    key: "brand_name",
    value: "MeetMatt",
    type: "text",
    description: "Brand name displayed in header",
  },
  {
    section: "global",
    key: "footer_copyright",
    value: "© 2025 MeetMatt. All rights reserved.",
    type: "text",
    description: "Footer copyright text",
  },

  // ============ HOMEPAGE / HERO ============
  {
    section: "hero",
    key: "headline",
    value: "Your AI Agent, Ready in Minutes",
    type: "text",
    description: "Main headline on homepage",
  },
  {
    section: "hero",
    key: "subheadline",
    value: "Deploy a custom AI agent that works 24/7 for your business",
    type: "text",
    description: "Subheadline below main headline",
  },
  {
    section: "hero",
    key: "cta_primary",
    value: "Create Your Agent",
    type: "text",
    description: "Primary CTA button text",
  },
  {
    section: "hero",
    key: "cta_secondary",
    value: "View Pricing",
    type: "text",
    description: "Secondary CTA button text",
  },
  {
    section: "hero",
    key: "badge_text",
    value: "New: Pro Plan Available",
    type: "text",
    description: "Badge text on hero section",
  },

  // ============ WIZARD STEPS ============
  {
    section: "wizard",
    key: "step_1_title",
    value: "Let's create your AI agent",
    type: "text",
    description: "Step 1: Welcome title",
  },
  {
    section: "wizard",
    key: "step_1_description",
    value: "In just a few steps, you'll have a custom AI agent ready to work for you 24/7.",
    type: "text",
    description: "Step 1: Welcome description",
  },
  {
    section: "wizard",
    key: "step_2_title",
    value: "What should we call your agent?",
    type: "text",
    description: "Step 2: Agent name title",
  },
  {
    section: "wizard",
    key: "step_2_placeholder",
    value: "e.g., Sarah, Helper Bot, Support Agent",
    type: "text",
    description: "Step 2: Name input placeholder",
  },
  {
    section: "wizard",
    key: "step_3_title",
    value: "What type of agent do you need?",
    type: "text",
    description: "Step 3: Agent type title",
  },
  {
    section: "wizard",
    key: "step_4_title",
    value: "What should your agent handle?",
    type: "text",
    description: "Step 4: Expectations title",
  },
  {
    section: "wizard",
    key: "step_5_title",
    value: "How should customers reach your agent?",
    type: "text",
    description: "Step 5: Channel selection title",
  },
  {
    section: "wizard",
    key: "step_6_title",
    value: "Enter your Telegram contact",
    type: "text",
    description: "Step 6: Telegram contact title",
  },
  {
    section: "wizard",
    key: "step_7_title",
    value: "Ready to deploy your agent?",
    type: "text",
    description: "Step 7: Payment/PRE-deploy title",
  },
  {
    section: "wizard",
    key: "step_8_title",
    value: "Deploying your agent...",
    type: "text",
    description: "Step 8: Deploy status title",
  },
  {
    section: "wizard",
    key: "step_8_success_title",
    value: "Your agent is ready! 🎉",
    type: "text",
    description: "Step 8: Deploy success title",
  },

  // ============ PRICING PAGE ============
  {
    section: "pricing",
    key: "page_title",
    value: "Simple, Transparent Pricing",
    type: "text",
    description: "Pricing page headline",
  },
  {
    section: "pricing",
    key: "page_subtitle",
    value: "Deploy AI agents for less than a cup of coffee per day",
    type: "text",
    description: "Pricing page subtitle",
  },
  {
    section: "pricing",
    key: "monthly_label",
    value: "Monthly",
    type: "text",
    description: "Monthly billing toggle label",
  },
  {
    section: "pricing",
    key: "annual_label",
    value: "Annual",
    type: "text",
    description: "Annual billing toggle label",
  },
  {
    section: "pricing",
    key: "annual_badge",
    value: "Save $800",
    type: "text",
    description: "Annual discount badge",
  },
  {
    section: "pricing",
    key: "daily_price_display",
    value: "$5",
    type: "text",
    description: "Daily price display (monthly plan)",
  },
  {
    section: "pricing",
    key: "daily_price_label",
    value: "/day",
    type: "text",
    description: "Daily price label",
  },
  {
    section: "pricing",
    key: "monthly_price_display",
    value: "$150",
    type: "text",
    description: "Monthly price display",
  },
  {
    section: "pricing",
    key: "monthly_price_period",
    value: "/mo",
    type: "text",
    description: "Monthly price period",
  },
  {
    section: "pricing",
    key: "annual_price_display",
    value: "$83",
    type: "text",
    description: "Annual price display (per month)",
  },
  {
    section: "pricing",
    key: "annual_price_subtitle",
    value: "Billed annually at $1000/year",
    type: "text",
    description: "Annual billing subtitle",
  },
  {
    section: "pricing",
    key: "setup_fee_original",
    value: "$250",
    type: "text",
    description: "Original setup fee (strikethrough)",
  },
  {
    section: "pricing",
    key: "setup_fee_current",
    value: "$150",
    type: "text",
    description: "Current setup fee",
  },
  {
    section: "pricing",
    key: "save_badge",
    value: "SAVE 40%",
    type: "text",
    description: "Setup fee discount badge",
  },
  {
    section: "pricing",
    key: "cta_button",
    value: "DEPLOY NOW",
    type: "text",
    description: "Main pricing CTA button",
  },
  {
    section: "pricing",
    key: "system_status",
    value: "SYSTEM ONLINE",
    type: "text",
    description: "System status indicator",
  },

  // ============ PRICING FEATURES ============
  {
    section: "pricing_features",
    key: "feature_1",
    value: "Live Build Viewing",
    type: "text",
    description: "Pricing feature 1",
  },
  {
    section: "pricing_features",
    key: "feature_2",
    value: "AI Powered",
    type: "text",
    description: "Pricing feature 2",
  },
  {
    section: "pricing_features",
    key: "feature_3",
    value: "Deploy Anywhere",
    type: "text",
    description: "Pricing feature 3",
  },
  {
    section: "pricing_features",
    key: "feature_4",
    value: "1 Month Included",
    type: "text",
    description: "Pricing feature 4",
  },

  // ============ TRUST BADGES ============
  {
    section: "trust_badges",
    key: "badge_1_label",
    value: "AI Powered",
    type: "text",
    description: "Trust badge 1 label",
  },
  {
    section: "trust_badges",
    key: "badge_1_desc",
    value: "Smart, capable agents",
    type: "text",
    description: "Trust badge 1 description",
  },
  {
    section: "trust_badges",
    key: "badge_2_label",
    value: "15-min Deploy",
    type: "text",
    description: "Trust badge 2 label",
  },
  {
    section: "trust_badges",
    key: "badge_2_desc",
    value: "From idea to live agent",
    type: "text",
    description: "Trust badge 2 description",
  },
  {
    section: "trust_badges",
    key: "badge_3_label",
    value: "60% Less Email",
    type: "text",
    description: "Trust badge 3 label",
  },
  {
    section: "trust_badges",
    key: "badge_3_desc",
    value: "Automated responses",
    type: "text",
    description: "Trust badge 3 description",
  },
  {
    section: "trust_badges",
    key: "badge_4_label",
    value: "500+ Founders",
    type: "text",
    description: "Trust badge 4 label",
  },
  {
    section: "trust_badges",
    key: "badge_4_desc",
    value: "Already using Matt",
    type: "text",
    description: "Trust badge 4 description",
  },

  // ============ PERFORMANCE METRICS ============
  {
    section: "metrics",
    key: "section_title",
    value: "Performance Metrics",
    type: "text",
    description: "Metrics section title",
  },
  {
    section: "metrics",
    key: "section_subtitle",
    value: "Real results from Matt deployments",
    type: "text",
    description: "Metrics section subtitle",
  },
  {
    section: "metrics",
    key: "stat_1_label",
    value: "First Response",
    type: "text",
    description: "Stat 1 label",
  },
  {
    section: "metrics",
    key: "stat_1_value",
    value: "< 60s",
    type: "text",
    description: "Stat 1 value",
  },
  {
    section: "metrics",
    key: "stat_1_vs",
    value: "4+ hours (typical)",
    type: "text",
    description: "Stat 1 comparison",
  },
  {
    section: "metrics",
    key: "stat_2_label",
    value: "Uptime SLA",
    type: "text",
    description: "Stat 2 label",
  },
  {
    section: "metrics",
    key: "stat_2_value",
    value: "99.9%",
    type: "text",
    description: "Stat 2 value",
  },
  {
    section: "metrics",
    key: "stat_2_vs",
    value: "95% (standard)",
    type: "text",
    description: "Stat 2 comparison",
  },
  {
    section: "metrics",
    key: "stat_3_label",
    value: "Concurrent Users",
    type: "text",
    description: "Stat 3 label",
  },
  {
    section: "metrics",
    key: "stat_3_value",
    value: "Unlimited",
    type: "text",
    description: "Stat 3 value",
  },
  {
    section: "metrics",
    key: "stat_3_vs",
    value: "Limited by agents",
    type: "text",
    description: "Stat 3 comparison",
  },
  {
    section: "metrics",
    key: "stat_4_label",
    value: "Cost Per Task",
    type: "text",
    description: "Stat 4 label",
  },
  {
    section: "metrics",
    key: "stat_4_value",
    value: "$0.02",
    type: "text",
    description: "Stat 4 value",
  },
  {
    section: "metrics",
    key: "stat_4_vs",
    value: "$2.50 (manual)",
    type: "text",
    description: "Stat 4 comparison",
  },

  // ============ COMPARISON TABLE ============
  {
    section: "comparison",
    key: "section_title",
    value: "MATT vs AGENCY",
    type: "text",
    description: "Comparison section title",
  },
  {
    section: "comparison",
    key: "section_subtitle",
    value: "Data-driven comparison for decision makers",
    type: "text",
    description: "Comparison section subtitle",
  },
  {
    section: "comparison",
    key: "column_metric",
    value: "Metric",
    type: "text",
    description: "Comparison table header - Metric",
  },
  {
    section: "comparison",
    key: "column_matt",
    value: "MATT",
    type: "text",
    description: "Comparison table header - Matt",
  },
  {
    section: "comparison",
    key: "column_agency",
    value: "Traditional Agency",
    type: "text",
    description: "Comparison table header - Agency",
  },

  // ============ ROI HIGHLIGHTS ============
  {
    section: "roi",
    key: "highlight_1_value",
    value: "$8,400",
    type: "text",
    description: "ROI highlight 1 value",
  },
  {
    section: "roi",
    key: "highlight_1_label",
    value: "Average annual savings",
    type: "text",
    description: "ROI highlight 1 label",
  },
  {
    section: "roi",
    key: "highlight_2_value",
    value: "624 hrs",
    type: "text",
    description: "ROI highlight 2 value",
  },
  {
    section: "roi",
    key: "highlight_2_label",
    value: "Time saved per year",
    type: "text",
    description: "ROI highlight 2 label",
  },
  {
    section: "roi",
    key: "highlight_3_value",
    value: "28x",
    type: "text",
    description: "ROI highlight 3 value",
  },
  {
    section: "roi",
    key: "highlight_3_label",
    value: "Return on investment",
    type: "text",
    description: "ROI highlight 3 label",
  },

  // ============ USE CASES ============
  {
    section: "use_cases",
    key: "section_title",
    value: "Automate Any Workflow",
    type: "text",
    description: "Use cases section title",
  },
  {
    section: "use_cases",
    key: "section_subtitle",
    value: "Hours saved per week by use case",
    type: "text",
    description: "Use cases section subtitle",
  },
  {
    section: "use_cases",
    key: "case_1_title",
    value: "Customer Support",
    type: "text",
    description: "Use case 1 title",
  },
  {
    section: "use_cases",
    key: "case_1_hours",
    value: "15 hrs/week",
    type: "text",
    description: "Use case 1 hours",
  },
  {
    section: "use_cases",
    key: "case_1_desc",
    value: "Instant responses",
    type: "text",
    description: "Use case 1 description",
  },
  {
    section: "use_cases",
    key: "case_1_icon",
    value: "🎧",
    type: "text",
    description: "Use case 1 icon (emoji)",
  },
  {
    section: "use_cases",
    key: "case_2_title",
    value: "Lead Qualification",
    type: "text",
    description: "Use case 2 title",
  },
  {
    section: "use_cases",
    key: "case_2_hours",
    value: "10 hrs/week",
    type: "text",
    description: "Use case 2 hours",
  },
  {
    section: "use_cases",
    key: "case_2_desc",
    value: "Auto-enrichment",
    type: "text",
    description: "Use case 2 description",
  },
  {
    section: "use_cases",
    key: "case_2_icon",
    value: "🎯",
    type: "text",
    description: "Use case 2 icon (emoji)",
  },
  {
    section: "use_cases",
    key: "case_3_title",
    value: "Scheduling",
    type: "text",
    description: "Use case 3 title",
  },
  {
    section: "use_cases",
    key: "case_3_hours",
    value: "8 hrs/week",
    type: "text",
    description: "Use case 3 hours",
  },
  {
    section: "use_cases",
    key: "case_3_desc",
    value: "Calendar sync",
    type: "text",
    description: "Use case 3 description",
  },
  {
    section: "use_cases",
    key: "case_3_icon",
    value: "📅",
    type: "text",
    description: "Use case 3 icon (emoji)",
  },
  {
    section: "use_cases",
    key: "case_4_title",
    value: "Data Entry",
    type: "text",
    description: "Use case 4 title",
  },
  {
    section: "use_cases",
    key: "case_4_hours",
    value: "12 hrs/week",
    type: "text",
    description: "Use case 4 hours",
  },
  {
    section: "use_cases",
    key: "case_4_desc",
    value: "Workflow automation",
    type: "text",
    description: "Use case 4 description",
  },
  {
    section: "use_cases",
    key: "case_4_icon",
    value: "📊",
    type: "text",
    description: "Use case 4 icon (emoji)",
  },

  // ============ CTA SECTION ============
  {
    section: "cta",
    key: "headline",
    value: "Ready to save 12+ hours per week?",
    type: "text",
    description: "CTA section headline",
  },
  {
    section: "cta",
    key: "subheadline",
    value: "Join founders who deploy AI agents in minutes, not months.",
    type: "text",
    description: "CTA section subheadline",
  },
  {
    section: "cta",
    key: "button_text",
    value: "Start Building Now",
    type: "text",
    description: "CTA button text",
  },
  {
    section: "cta",
    key: "pricing_note_monthly",
    value: "$150 first month • $150/mo after",
    type: "text",
    description: "CTA pricing note (monthly)",
  },
  {
    section: "cta",
    key: "pricing_note_annual",
    value: "$1000/year (save $800) • $150 one-time setup",
    type: "text",
    description: "CTA pricing note (annual)",
  },

  // ============ DASHBOARD / BILLING ============
  {
    section: "dashboard",
    key: "welcome_title",
    value: "Welcome back",
    type: "text",
    description: "Dashboard welcome title",
  },
  {
    section: "dashboard",
    key: "no_agents_title",
    value: "No agents yet",
    type: "text",
    description: "No agents message title",
  },
  {
    section: "dashboard",
    key: "no_agents_description",
    value: "Create your first AI agent to get started.",
    type: "text",
    description: "No agents message description",
  },
  {
    section: "dashboard",
    key: "create_agent_button",
    value: "Create Agent",
    type: "text",
    description: "Create agent button text",
  },

  // ============ BILLING PAGE ============
  {
    section: "billing",
    key: "page_title",
    value: "Billing & Settings",
    type: "text",
    description: "Billing page title",
  },
  {
    section: "billing",
    key: "page_subtitle",
    value: "Manage your subscriptions, payments, and account preferences",
    type: "text",
    description: "Billing page subtitle",
  },
  {
    section: "billing",
    key: "subscriptions_section_title",
    value: "Your Subscriptions",
    type: "text",
    description: "Subscriptions section title",
  },
  {
    section: "billing",
    key: "extend_button",
    value: "Extend & Save",
    type: "text",
    description: "Extend subscription button",
  },
  {
    section: "billing",
    key: "renew_button",
    value: "Renew Now",
    type: "text",
    description: "Renew subscription button",
  },
  {
    section: "billing",
    key: "payment_methods_title",
    value: "Payment Methods",
    type: "text",
    description: "Payment methods section title",
  },
  {
    section: "billing",
    key: "notifications_title",
    value: "Notifications",
    type: "text",
    description: "Notifications section title",
  },
  {
    section: "billing",
    key: "security_title",
    value: "Security",
    type: "text",
    description: "Security section title",
  },

  // ============ PAYMENT MODAL ============
  {
    section: "payment_modal",
    key: "title",
    value: "Extend Subscription",
    type: "text",
    description: "Payment modal title",
  },
  {
    section: "payment_modal",
    key: "select_duration_label",
    value: "Select Duration",
    type: "text",
    description: "Duration selector label",
  },
  {
    section: "payment_modal",
    key: "proceed_button",
    value: "Proceed to Payment",
    type: "text",
    description: "Proceed to payment button",
  },
  {
    section: "payment_modal",
    key: "payment_created_title",
    value: "Payment Created",
    type: "text",
    description: "Payment created success title",
  },
  {
    section: "payment_modal",
    key: "payment_instructions",
    value: "Send the exact amount to the address below",
    type: "text",
    description: "Payment instructions",
  },
  {
    section: "payment_modal",
    key: "confirmation_note",
    value: "Payment will be confirmed automatically once received. This may take a few minutes.",
    type: "text",
    description: "Payment confirmation note",
  },

  // ============ FOOTER LINKS ============
  {
    section: "footer",
    key: "link_privacy",
    value: "Privacy Policy",
    type: "text",
    description: "Footer privacy link",
  },
  {
    section: "footer",
    key: "link_terms",
    value: "Terms of Service",
    type: "text",
    description: "Footer terms link",
  },
  {
    section: "footer",
    key: "link_pricing",
    value: "Pricing",
    type: "text",
    description: "Footer pricing link",
  },
  {
    section: "footer",
    key: "link_support",
    value: "Support",
    type: "text",
    description: "Footer support link",
  },
];

// Helper function to get content by section
export function getContentBySection(section: string): ContentItem[] {
  return defaultWebsiteContent.filter((item) => item.section === section);
}

// Helper function to get a specific content item
export function getContentValue(section: string, key: string): string {
  const item = defaultWebsiteContent.find((item) => item.section === section && item.key === key);
  return item?.value || "";
}
